-- Suki Rewards minimal schema + seed
-- Safe to run multiple times.

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  phone TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  tier TEXT NOT NULL,
  birthday DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS member_state (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  points INTEGER NOT NULL DEFAULT 0,
  birthday_reward_claimed BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS coupon_wallet (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  coupon_id TEXT NOT NULL,
  type TEXT NOT NULL,
  value TEXT NOT NULL,
  title TEXT NOT NULL,
  "desc" TEXT NOT NULL,
  expire_at DATE NOT NULL,
  tag TEXT,
  used BOOLEAN NOT NULL DEFAULT FALSE,
  unlocked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, coupon_id)
);

-- demo account: 0917-123-4567 / 123456
-- bcrypt hash generated by bcryptjs (10 rounds)
INSERT INTO users (phone, password_hash, name, tier, birthday)
VALUES ('0917-123-4567', '$2b$10$7I6ClYkiUjRkXeysv12QmucHa5NYVHGtTWAJR4.bVKLEDrjZVqZQS', 'Maria Santos', 'Gold', DATE '2026-03-15')
ON CONFLICT (phone) DO NOTHING;

INSERT INTO member_state (user_id, points, birthday_reward_claimed)
SELECT id, 2450, FALSE
FROM users
WHERE phone = '0917-123-4567'
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO coupon_wallet (user_id, coupon_id, type, value, title, "desc", expire_at, tag, used)
SELECT u.id, c.coupon_id, c.type, c.value, c.title, c."desc", c.expire_at, c.tag, c.used
FROM users u
JOIN (
  VALUES
    ('C001', 'percent', '20', '20% OFF', 'Any purchase', DATE '2026-03-31', NULL, FALSE),
    ('C002', 'fixed', '50', '₱50 OFF', 'Min. spend ₱300', DATE '2026-04-15', NULL, FALSE),
    ('C003', 'gift', 'FREE Dessert', 'FREE Dessert', 'With any meal', DATE '2026-03-20', NULL, FALSE),
    ('C004', 'percent', '10', '10% OFF Coffee', 'Coffee only', DATE '2026-02-28', NULL, TRUE)
) AS c(coupon_id, type, value, title, "desc", expire_at, tag, used)
ON u.phone = '0917-123-4567'
ON CONFLICT (user_id, coupon_id) DO NOTHING;
